name: FreeBSD

on:
  push:
    branches:
      - main

jobs:
  build-binary-for-freebsd:
    runs-on: macos-12

    env:
      CONFIG: "--disable-benchmarks --disable-documentation"

    steps:
      - uses: actions/checkout@v3

      - name: FreeBSD-VM
        id: build-freebsd
        uses: vmactions/freebsd-vm@v0.2.0
        with:
          release: 12.3
          envs: "CONFIG"
          usesh: true
          mem: 4096
          run: |
            # Switch to latest branch.
            mkdir -p /usr/local/etc/pkg/repos
            echo 'FreeBSD: { url: "pkg+https://pkg.FreeBSD.org/${ABI}/latest" }' > /usr/local/etc/pkg/repos/FreeBSD.conf
            pkg update

            # Install dependencies.
            # The GHC 8.10 port only contains the versioned ghc binary,
            # so we provide a symlink here because Cabal requires it.
            pkg install -y ghc810 hs-cabal-install
            ln -s /usr/local/bin/ghc-8.10.7 /usr/local/bin/ghc

            # Disable generation of documentation. Overriding this via cli
            # flags is broken.
            sed -i '.bak' 's/documentation: True/documentation: False/' cabal.project

            # Build and test project.
            cabal update
            cabal build $CONFIG all
            cabal test $CONFIG all
            cabal install --enable-executable-static --install-method=copy --overwrite-policy=always --installdir=dist/
            mv dist/eselsohr-exe dist/eselsohr

      - name: Store application binary as artifact
        uses: actions/upload-artifact@v2
        with:
          name: eselsohr
          path: dist/eselsohr

